azs:
- cloud_properties:
    datacenters:
    - clusters:
      - Lab09-Cluster01: {}
  name: z1
- cloud_properties:
    datacenters:
    - clusters:
      - Lab09-Cluster01: {}
  name: z2
- cloud_properties:
    datacenters:
    - clusters:
      - Lab09-Cluster01: {}
  name: z3
compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: default
  workers: 5
disk_types:
- disk_size: 3000
  name: default
- disk_size: 50000
  name: large
networks:
- name: default
  subnets:
  - static: [172.28.97.51-172.28.97.60]
    azs:
    - z1
    - z2
    - z3
    cloud_properties:
      name: Lab09-NetG
    dns:
    - 172.29.0.5
    gateway: 172.28.97.1
    range: 172.28.97.0/24
    reserved:
    - 172.28.97.1-172.28.97.50
  type: manual
vm_types:
- cloud_properties:
    cpu: 2
    disk: 3240
    ram: 1024
  name: default
- cloud_properties:
    cpu: 2
    disk: 30240
    ram: 4096
  name: large
- cloud_properties:
    cpu: 2
    disk: 120960
    ram: 4096
  name: large-disk
